In [13]:
import pandas as pd
import numpy as np
data= pd.DataFrame({
    'Originalfeature':[1,2,3,4,5,6,7],
    'categoricalfeature':['A','B','B','A','B','A','A']
})
data

   Originalfeature categoricalfeature
0                1                  A
1                2                  B
2                3                  B
3                4                  A
4                5                  B
5                6                  A
6                7                  A

In [14]:
# one-Hot Encoding
data1= pd.get_dummies(data,columns=['categoricalfeature'])
data1

   Originalfeature  categoricalfeature_A  categoricalfeature_B
0                1                  True                 False
1                2                 False                  True
2                3                 False                  True
3                4                  True                 False
4                5                 False                  True
5                6                  True                 False
6                7                  True                 False

In [15]:
data1= pd.get_dummies(data,columns=['categoricalfeature'],drop_first=True)
data1

   Originalfeature  categoricalfeature_B
0                1                 False
1                2                  True
2                3                  True
3                4                 False
4                5                  True
5                6                 False
6                7                 False

In [16]:
df=pd.read_csv("car data.csv")
df

    Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner
0       ritz  2014           3.35           5.59       27000    Petrol      Dealer       Manual      0
1        sx4  2013           4.75           9.54       43000    Diesel      Dealer       Manual      0
2       ciaz  2017           7.25           9.85        6900    Petrol      Dealer       Manual      0
3    wagon r  2011           2.85           4.15        5200    Petrol      Dealer       Manual      0
4      swift  2014           4.60           6.87       42450    Diesel      Dealer       Manual      0
..       ...   ...            ...            ...         ...       ...         ...          ...    ...
296     city  2016           9.50          11.60       33988    Diesel      Dealer       Manual      0
297     brio  2015           4.00           5.90       60000    Petrol      Dealer       Manual      0
298     city  2009           3.35          11.00       87934    Petrol      Dealer       Manual      0
299     city  2017          11.50          12.50        9000    Diesel      Dealer       Manual      0
300     brio  2016           5.30           5.90        5464    Petrol      Dealer       Manual      0

[301 rows x 9 columns]

In [17]:
df.head(10)

        Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner
0           ritz  2014           3.35           5.59       27000    Petrol      Dealer       Manual      0
1            sx4  2013           4.75           9.54       43000    Diesel      Dealer       Manual      0
2           ciaz  2017           7.25           9.85        6900    Petrol      Dealer       Manual      0
3        wagon r  2011           2.85           4.15        5200    Petrol      Dealer       Manual      0
4          swift  2014           4.60           6.87       42450    Diesel      Dealer       Manual      0
5  vitara brezza  2018           9.25           9.83        2071    Diesel      Dealer       Manual      0
6           ciaz  2015           6.75           8.12       18796    Petrol      Dealer       Manual      0
7        s cross  2015           6.50           8.61       33429    Diesel      Dealer       Manual      0
8           ciaz  2016           8.75           8.89       20273    Diesel      Dealer       Manual      0
9           ciaz  2015           7.45           8.92       42367    Diesel      Dealer       Manual      0

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

In [19]:
df.nunique()

Car_Name          98
Year              16
Selling_Price    156
Present_Price    147
Kms_Driven       206
Fuel_Type          3
Seller_Type        2
Transmission       2
Owner              3
dtype: int64

In [20]:
df.drop('Car_Name',axis=1,inplace=True)

In [12]:
df

     Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner
0    2014           3.35           5.59       27000    Petrol      Dealer       Manual      0
1    2013           4.75           9.54       43000    Diesel      Dealer       Manual      0
2    2017           7.25           9.85        6900    Petrol      Dealer       Manual      0
3    2011           2.85           4.15        5200    Petrol      Dealer       Manual      0
4    2014           4.60           6.87       42450    Diesel      Dealer       Manual      0
..    ...            ...            ...         ...       ...         ...          ...    ...
296  2016           9.50          11.60       33988    Diesel      Dealer       Manual      0
297  2015           4.00           5.90       60000    Petrol      Dealer       Manual      0
298  2009           3.35          11.00       87934    Petrol      Dealer       Manual      0
299  2017          11.50          12.50        9000    Diesel      Dealer       Manual      0
300  2016           5.30           5.90        5464    Petrol      Dealer       Manual      0

[301 rows x 8 columns]

In [21]:
pd.get_dummies(df)

     Year  Selling_Price  Present_Price  ...  Seller_Type_Individual  Transmission_Automatic  Transmission_Manual
0    2014           3.35           5.59  ...                   False                   False                 True
1    2013           4.75           9.54  ...                   False                   False                 True
2    2017           7.25           9.85  ...                   False                   False                 True
3    2011           2.85           4.15  ...                   False                   False                 True
4    2014           4.60           6.87  ...                   False                   False                 True
..    ...            ...            ...  ...                     ...                     ...                  ...
296  2016           9.50          11.60  ...                   False                   False                 True
297  2015           4.00           5.90  ...                   False                   False                 True
298  2009           3.35          11.00  ...                   False                   False                 True
299  2017          11.50          12.50  ...                   False                   False                 True
300  2016           5.30           5.90  ...                   False                   False                 True

[301 rows x 12 columns]

In [22]:
pd.get_dummies(df,drop_first=True)

     Year  Selling_Price  Present_Price  ...  Fuel_Type_Petrol  Seller_Type_Individual  Transmission_Manual
0    2014           3.35           5.59  ...              True                   False                 True
1    2013           4.75           9.54  ...             False                   False                 True
2    2017           7.25           9.85  ...              True                   False                 True
3    2011           2.85           4.15  ...              True                   False                 True
4    2014           4.60           6.87  ...             False                   False                 True
..    ...            ...            ...  ...               ...                     ...                  ...
296  2016           9.50          11.60  ...             False                   False                 True
297  2015           4.00           5.90  ...              True                   False                 True
298  2009           3.35          11.00  ...              True                   False                 True
299  2017          11.50          12.50  ...             False                   False                 True
300  2016           5.30           5.90  ...              True                   False                 True

[301 rows x 9 columns]

## Adding a new Feature

In [23]:
room_length=[18,20,10,12,18,11]
r_breadth=[20,20,10,11,19,10]
r_type=['Big','Big','N','N','Big','N']
data=pd.DataFrame({'Length':room_length,'Breadth':r_breadth,'Type':r_type})
data

   Length  Breadth Type
0      18       20  Big
1      20       20  Big
2      10       10    N
3      12       11    N
4      18       19  Big
5      11       10    N

In [26]:
data['Area']=data['Length']*data['Breadth']
data

   Length  Breadth Type  Area
0      18       20  Big   360
1      20       20  Big   400
2      10       10    N   100
3      12       11    N   132
4      18       19  Big   342
5      11       10    N   110

In [27]:
data[data['Area']>150]

   Length  Breadth Type  Area
0      18       20  Big   360
1      20       20  Big   400
4      18       19  Big   342

## Encoding Nominal Variables

In [ ]:
# Using one-hot encoding method

## np.where()

In [32]:
area=[4720,2430,1203,4561,1205]
price=[236,256,300,500,230]
data4=pd.DataFrame({'Area':area,'Price':price})
data4

   Area  Price
0  4720    236
1  2430    256
2  1203    300
3  4561    500
4  1205    230

In [33]:
data4['Price']=np.where(data4['Price']>=300,'High',np.where(data4['Price']<200,'Low','Medium'))
data4

   Area   Price
0  4720  Medium
1  2430  Medium
2  1203    High
3  4561    High
4  1205  Medium

## train_test_split()

In [34]:
from sklearn.model_selection import train_test_split

# x always in DataFrame
# y always in Series

## Arithmetic Operation on Series & DataFrame

In [ ]:
# NaN + 1 = NaN

In [35]:
df1=pd.DataFrame({'A':[1,2,None],'B':[4,None,6]})
df2=pd.DataFrame({'A':[None,2,0],'B':[None,1,67]})

result=df1+df2
result

     A     B
0  NaN   NaN
1  4.0   NaN
2  NaN  73.0

In [37]:

result=df1/df2
result

     A         B
0  NaN       NaN
1  1.0       NaN
2  NaN  0.089552

In [ ]:
# Dash Cross validation ny aave

In [38]:
df=pd.read_csv("ipl-matches.csv")
df

          ID        City        Date  ...                                       Team2Players        Umpire1         Umpire2
0    1312200   Ahmedabad  2022-05-29  ...  ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...    CB Gaffaney     Nitin Menon
1    1312199   Ahmedabad  2022-05-27  ...  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...    CB Gaffaney     Nitin Menon
2    1312198     Kolkata  2022-05-25  ...  ['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...  J Madanagopal        MA Gough
3    1312197     Kolkata  2022-05-24  ...  ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...   BNJ Oxenford       VK Sharma
4    1304116      Mumbai  2022-05-22  ...  ['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...   AK Chaudhary   NA Patwardhan
..       ...         ...         ...  ...                                                ...            ...             ...
945   335986     Kolkata  2008-04-20  ...  ['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...      BF Bowden     K Hariharan
946   335985      Mumbai  2008-04-20  ...  ['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...       SJ Davis       DJ Harper
947   335984       Delhi  2008-04-19  ...  ['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...      Aleem Dar  GA Pratapkumar
948   335983  Chandigarh  2008-04-19  ...  ['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...      MR Benson      SL Shastri
949   335982   Bangalore  2008-04-18  ...  ['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...      Asad Rauf     RE Koertzen

[950 rows x 20 columns]

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 148.6+ KB